Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Max: 30

Style/MixinUsage:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
