require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-yayoi

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 140
  Exclude:
    - 'spec/**/*'

Style/MixinUsage:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Lint/UriEscapeUnescape:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
