AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Style/MixinUsage:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Lint/UriEscapeUnescape:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
