env:
  global:
    - CC_TEST_REPORTER_ID=c4d8f2b21e4a0af7b3fd7d4c679296b36840811826fff835064dae9ffca2231f
language: ruby
rvm:
  - 2.5.3
services: postgresql
bundler_args: "--without development --deployment -j4"
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_install:
  - nvm install 6.11.2
  - npm config set spin false
  - npm install -g yarn
  - yarn global add greenkeeper-lockfile@1
before_script:
  - yarn
  - cp config/database.travis.yml config/database.yml
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - greenkeeper-lockfile-upload
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
  - bundle exec rubocop
  - bundle exec reek /app -c .todo.reek
  - bundle exec brakeman
  - bundle exec rspec
notifications:
  email:
    recipients:
      - you.goto.510@gmail.com
    on_success: never
    on_failure: always
