version: '3'
services:
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    volumes:
      - .:/myapp
      - bundle:/bundle
    ports:
      - '3035:3035'

  web:
    build: .
    command: /bin/bash -c 'rm -rf tmp/pids/server.pid; bundle exec rails s -b 0.0.0.0'
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: webpacker:3035
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/myapp
      - bundle:/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - webpacker
    tty: true
    stdin_open: true

volumes:
  store:
    driver: local
  bundle:
    driver: local

