default: &default
  weapon_index_analysis:
    analysis:
      tokenizer:
        kuromoji_tokenizer:
          type: kuromoji_tokenizer
          mode: search
      filter:
        pos_filter:
          type: kuromoji_part_of_speech
          stoptags:
            - 助詞-格助詞-一般
            - 助詞-終助詞
        greek_lowercase_filter:
          type: lowercase
          language: greek
      analyzer:
        kuromoji_analyzer:
          type: custom
          tokenizer: kuromoji_tokenizer
          filter:
            - kuromoji_baseform
            - pos_filter
            - greek_lowercase_filter

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
